"""Pydantic models for multi-turn conversation turns.

Conforms to the conversation_turn schema defined in
internal-api.yaml section on POST /interpret (v1.1.0).
Used in conversation_history for multi-turn interpretation
and in the InterpretationClarificationNeeded stream event.
"""

from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field


class ClarificationOption(BaseModel):
    """A structured choice presented to the user in a clarification question.

    Attributes:
        option_id: Unique identifier for this option within the question.
        label: Short display label for the option.
        description: Optional longer explanation of the option.
    """

    option_id: str
    label: str
    description: str | None = None


class ClarificationQuestion(BaseModel):
    """A clarification question generated by the Interpreter.

    The Interpreter asks this when the query is ambiguous and it needs
    more information before producing a plan. The clarification_id is
    generated by the parser (not the LLM).

    Attributes:
        clarification_id: UUID generated by the parser.
        question: The clarification question in natural language.
        options: Optional structured choices for the user.
        allows_free_text: Whether the user can type a free-text response.
    """

    clarification_id: str
    question: str
    options: list[ClarificationOption] | None = None
    allows_free_text: bool = True


class AssistantTurn(BaseModel):
    """An assistant turn in the conversation history.

    Contains the AI's analysis text from a previous interpretation turn,
    and optionally the clarification question that was asked.

    Attributes:
        role: Always "assistant" for this turn type.
        content: The AI's analysis text (accumulated text_delta values).
        clarification: The clarification question asked, if any.
    """

    role: Literal["assistant"]
    content: str
    clarification: ClarificationQuestion | None = None


class UserTurn(BaseModel):
    """A user turn in the conversation history.

    Contains the user's response to a clarification question, either
    by selecting an option or providing free text.

    Attributes:
        role: Always "user" for this turn type.
        response_type: Whether the user selected an option or typed free text.
        selected_option_id: The option_id chosen (for option_selection).
        text: Free-text response or additional context.
    """

    role: Literal["user"]
    response_type: Literal["option_selection", "free_text"]
    selected_option_id: str | None = None
    text: str | None = None


ConversationTurn = Annotated[
    Union[AssistantTurn, UserTurn],
    Field(discriminator="role"),
]
