"""Pydantic models for query plan schemas.

Conforms to the query_plan and plan_step schemas defined in
mcp-tool-interface.yaml section 2.
"""

from typing import Any, Literal

from pydantic import BaseModel, Field


class FilterCondition(BaseModel):
    """A filter condition applied to array items within a transform.

    Attributes:
        field: The field within each array item to test.
        operator: The comparison operator.
        value: The value to compare against. Ignored for is_null/is_not_null.
    """

    field: str
    operator: Literal[
        "equals",
        "not_equals",
        "greater_than",
        "less_than",
        "is_null",
        "is_not_null",
        "contains",
        "not_contains",
        "before",
        "after",
    ]
    value: Any | None = None


class TransformFilter(BaseModel):
    """A filter expression applied to array results.

    Attributes:
        array_path: Dot-path to the array within the tool's output to filter.
        condition: The filter condition to apply.
    """

    array_path: str
    condition: FilterCondition


class Transform(BaseModel):
    """Optional transformation applied to a tool's raw output.

    Attributes:
        filter: A filter expression for array results.
        select_fields: Fields to retain from each item in the result.
    """

    filter: TransformFilter | None = None
    select_fields: list[str] | None = None


class IterateOver(BaseModel):
    """Directive to execute a step once per item in a previous step's array output.

    Attributes:
        source_step: The step_id whose output contains the array.
        array_path: Dot-path to the array within the source step's output.
        item_alias: Name used to reference the current iteration item.
    """

    source_step: str
    array_path: str
    item_alias: str


class PlanStep(BaseModel):
    """A single step within a query plan.

    Conforms to the plan_step schema in mcp-tool-interface.yaml.

    Attributes:
        step_id: Unique identifier within the plan (e.g., "step_1").
        tool_name: The MCP tool to invoke.
        integration_id: The integration to execute against.
        parameters: Parameters to pass to the MCP tool.
        description: Human-readable explanation of this step.
        output_alias: Descriptive name for this step's output.
        transform: Optional transformation on the tool's raw output.
        depends_on: Step IDs that must complete before this step.
        iterate_over: Directive to iterate over a previous step's array output.
        paginate: Whether to automatically handle pagination. Defaults to True.
    """

    step_id: str
    tool_name: str
    integration_id: str
    parameters: dict = Field(default_factory=dict)
    description: str
    output_alias: str
    transform: Transform | None = None
    depends_on: list[str] | None = None
    iterate_over: IterateOver | None = None
    paginate: bool = True


class QueryPlan(BaseModel):
    """Complete execution plan generated by the Interpreter.

    Conforms to the query_plan schema in mcp-tool-interface.yaml.

    Attributes:
        plan_id: UUID for this plan.
        plan_version: Schema version of the plan format.
        steps: Ordered list of execution steps. Must have at least one.
        estimated_tool_calls: Estimated total MCP tool invocations.
        summary: Human-readable explanation of the plan.
    """

    plan_id: str
    plan_version: str = "1.0"
    steps: list[PlanStep] = Field(min_length=1)
    estimated_tool_calls: int
    summary: str
